name: test-docker
sorters:
  -
    name: kilosort3
    algorithm: kilosort3
    sorting_params: {}
  -
    name: kilosort2_5
    algorithm: kilosort2_5
    sorting_params: {}
studies:
  -
    study_set_name: PAIRED_KAMPFF
    study_name: paired_kampff
    recording_names:
      - 2014_11_25_Pair_3_0
    sorter_names:
      - kilosort3
      - kilosort2_5