#!/bin/bash

# 2/15/22
# https://www.figurl.org/f?v=gs://figurl/spikeforestview-1&d=902f00af1b7d4a4e36c2c916ee8a9b8e3992ef67&channel=flatiron1&label=SF%20workflow%20results%3A%20kilosort

set -ex

./workflow

./prepare-recording
./prepare-sorting-true

./sorting-metrics

./kilosort3
./kilosort2_5
./kilosort2

./compare

./sorting-figurl

./results-figurl