#!/bin/bash

# 2/11/22
# https://figurl.org/f?v=gs://figurl/spikeforestview-1&d=7b210db7fb1f0bb304065aaaaf59f9c3c565a982&channel=flatiron1&label=SF%20workflow%20results%3A%20flatiron

set -ex

./workflow

./prepare-recording
./prepare-sorting-true

./sorting-metrics

./kilosort3
./kilosort2_5
./kilosort2

./compare

./sorting-figurl

./results-figurl