#!/bin/bash

# 2/8/22
# https://figurl.org/f?v=gs://figurl/spikeforestview-1&d=e3360c9f167e257af196cf0e34128fdeb1e4c9be&channel=flatiron1&label=SF%20workflow%20results%3A%20flatiron

set -ex

./workflow
./prepare
./workflow

./mountainsort4

./spykingcircus

./tridesclous

./workflow
./compare
./workflow

./figurl-results