name: flatiron
sorters:
  -
    name: mountainsort4
    algorithm: mountainsort4
    sorting_params:
      detect_sign: -1
      adjacency_radius: 50
      freq_min: 300
      freq_max: 6000
      filter: True
      whiten: True
      clip_size: 50
      detect_threshold: 3
      detect_interval: 10
  -
    name: spykingcircus
    algorithm: spykingcircus
    sorting_params: {}
  -
    name: tridesclous
    algorithm: tridesclous
    sorting_params: {}
studies:
  -
    study_set_name: PAIRED_BOYDEN
    study_name: paired_boyden32c
    recording_names:
      - "1103_1_1"
    sorter_names:
      - mountainsort4
      - spykingcircus
  -
    study_set_name: PAIRED_CRCNS_HC1
    study_name: paired_crcns
    recording_names:
      - "d11221_d11221.001"
    sorter_names:
      - mountainsort4
      - spykingcircus
  -
    study_set_name: PAIRED_ENGLISH
    study_name: paired_english
    recording_names:
      - "m108_191125_163508"
    sorter_names:
      - mountainsort4
      - spykingcircus
  -
    study_set_name: PAIRED_KAMPFF
    study_name: paired_kampff
    recording_names:
      - 2014_11_25_Pair_3_0
      - 2015_09_03_Pair_9_0A
    sorter_names:
      - mountainsort4
      - spykingcircus
  -
    study_set_name: PAIRED_MEA64C_YGER
    study_name: paired_mea64c
    recording_names:
      - "20160415_patch2"
    sorter_names:
      - mountainsort4
      - spykingcircus
  -
    study_set_name: SYNTH_MAGLAND
    study_name: synth_magland_noise10_K10_C4
    recording_names:
      - 001_synth
      - 002_synth
    sorter_names:
      - mountainsort4
      - spykingcircus