#!/bin/bash

export BASEDIR="../.."

$BASEDIR/scripts/sorting.py \
    config.yaml spykingcircus \
    --singularity --image docker://docker.flatironinstitute.org/magland/spykingcircus-rar \
    "$@"

./workflow